"""Generates the secondary pages of the Frutatt site from FLAVORS below.

  python build_pages.py   -> site/sabores.html, site/<flavor>.html, site/contato.html

index.html is hand-written; everything else comes from here so all pages share the
same header, footer, contact links and motion hooks. Instagram/WhatsApp live in
site/config.js (one place, every page).
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(ROOT, "site")

# Facts are ONLY what is printed on each label. Keep them in sync with the packaging.
FLAVORS = [
    {
        "slug": "caju", "name": "Caju", "page": True,
        "title_lines": [["O", "sabor"], ["do", "*caju,"], ["de", "verdade."]],
        "lead": "28% de fruta, sem conservantes e fonte de vitamina C. Agite antes de beber.",
        "facts": [("28%", "de fruta"), ("Sem", "conservantes"), ("0%", "açúcar"), ("Vit. C", "fonte de vitamina C")],
        "type": "Bebida de fruta adoçada", "card": "O clássico do Nordeste, gelado.",
    },
    {
        "slug": "uva", "name": "Uva", "page": True,
        "title_lines": [["Experimente"], ["o", "sabor"], ["da", "*uva."]],
        "lead": "Uva encorpada, com 35% de polpa, na garrafinha de 300 ml.",
        "facts": [("35%", "de polpa"), ("300 ml", "volume líquido")],
        "type": "Bebida de fruta adoçada", "card": "Encorpado e intenso.",
    },
    {
        "slug": "caja", "name": "Cajá", "page": True,
        "title_lines": [["Cajá"], ["*zero", "*açúcar,"], ["todo", "sabor."]],
        "lead": "Zero açúcar e 20% de polpa. Bebida de fruta de baixa caloria.",
        "facts": [("Zero", "açúcar"), ("20%", "de polpa"), ("300 ml", "volume líquido")],
        "type": "Bebida de fruta de baixa caloria", "card": "Zero açúcar, azedinho na medida.",
    },
    {"slug": "granola", "name": "Granola", "page": False, "card": "Em breve."},
    {"slug": "acai", "name": "Açaí", "page": False, "card": "Em breve."},
]
PAGES = [f for f in FLAVORS if f["page"]]


def pic(name, widths, sizes, alt, *, lazy=True, extra="", ratio=(757, 1437)):
    avif = ", ".join(f"img/{name}-{w}.avif {w}w" for w in widths)
    webp = ", ".join(f"img/{name}-{w}.webp {w}w" for w in widths)
    load = 'loading="lazy" ' if lazy else 'fetchpriority="high" '
    return (f'<picture><source type="image/avif" srcset="{avif}" sizes="{sizes}">'
            f'<img src="img/{name}-{widths[1]}.webp" srcset="{webp}" sizes="{sizes}" '
            f'width="{ratio[0]}" height="{ratio[1]}" alt="{alt}" {load}decoding="async"{extra}></picture>')


def header(active):
    links = [("index.html", "Início"), ("sabores.html", "Sabores"), ("contato.html", "Contato")]
    nav = "\n      ".join(
        f'<a href="{h}"{" aria-current=\"page\"" if h == active else ""}>{t}</a>' for h, t in links)
    return f'''<a class="skip" href="#conteudo">Pular para o conteúdo</a>
  <header class="nav">
    <a class="nav__brand" href="index.html" aria-label="Suco Frutatt — início">Suco Frutatt</a>
    <nav aria-label="Principal">
      {nav}
    </nav>
  </header>'''


FOOTER = '''<footer class="footer">
    <div class="footer__links">
      <a data-contact="instagram" hidden>Instagram</a>
      <a data-contact="whatsapp" hidden>WhatsApp</a>
    </div>
    <p>© 2026 Frutatt</p>
  </footer>
  <a class="wa-fab" data-contact="whatsapp" hidden aria-label="Fale com a Frutatt no WhatsApp">
    <svg viewBox="0 0 24 24" width="28" height="28" aria-hidden="true"><path fill="currentColor" d="M12 2a10 10 0 0 0-8.6 15.1L2 22l5-1.3A10 10 0 1 0 12 2Zm0 18.2a8.2 8.2 0 0 1-4.2-1.2l-.3-.2-3 .8.8-2.9-.2-.3A8.2 8.2 0 1 1 12 20.2Zm4.5-6.1c-.2-.1-1.5-.7-1.7-.8-.2-.1-.4-.1-.6.1l-.8 1c-.1.2-.3.2-.5.1a6.7 6.7 0 0 1-3.3-2.9c-.2-.4.2-.4.7-1.3.1-.2 0-.3 0-.4l-.8-1.8c-.2-.5-.4-.4-.6-.4h-.5a1 1 0 0 0-.7.3 3 3 0 0 0-.9 2.2 5.2 5.2 0 0 0 1.1 2.7 11.8 11.8 0 0 0 4.5 4c1.7.7 2.3.8 3.2.6a2.7 2.7 0 0 0 1.8-1.2 2.2 2.2 0 0 0 .1-1.3c0-.1-.2-.2-.4-.3Z"/></svg>
  </a>'''


def doc(title, desc, flavor, active, body, preload=""):
    return f'''<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta name="description" content="{desc}">
  <script>document.documentElement.classList.add('js')</script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@700;800&family=Figtree:wght@400;500;600;700&display=swap" rel="stylesheet">
  {preload}
  <link rel="stylesheet" href="styles.css">
</head>
<body data-flavor="{flavor}">
  <!-- generated by build_pages.py — edit the generator, not this file -->
  {header(active)}
  <main id="conteudo">
{body}
  </main>
  {FOOTER}
  <script src="config.js"></script>
  <script src="img/layers.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js" defer></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js" defer></script>
  <script src="main.js" defer></script>
</body>
</html>
'''


def title_html(lines):
    out = []
    for line in lines:
        words = " ".join(
            f'<span class="word accent">{w[1:]}</span>' if w.startswith("*") else f'<span class="word">{w}</span>'
            for w in line)
        out.append(f'<span class="line">{words}</span>')
    return "\n            ".join(out)


def bg_name(slug):
    return "bg" if slug == "caju" else f"bg-{slug}"


def flavor_page(f, nxt):
    bg = bg_name(f["slug"])
    sizes = "max(100vw, 178svh)"
    chips = "\n          ".join(f'<li data-intro="fact"><strong>{a}</strong> {b}</li>' for a, b in f["facts"][:3])
    facts = "\n        ".join(
        f'<li class="why__item" data-reveal><strong>{a}</strong><span>{b}</span></li>' for a, b in f["facts"])
    preload = (f'<link rel="preload" as="image" type="image/avif" imagesrcset="img/{bg}-960.avif 960w, '
               f'img/{bg}-1440.avif 1440w, img/{bg}-1920.avif 1672w" imagesizes="{sizes}">')
    body = f'''    <section class="hero" id="topo" aria-labelledby="hero-title">
      <div class="hero__stage" data-depth="bg" aria-hidden="true">
        {pic(bg, [960, 1440, 1920], sizes, "", lazy=False, ratio=(1672, 941)).replace("<img ", '<img class="hero__plate" ')}
        <div class="hero__leaves" data-leaves="far"></div>
      </div>
      <div class="hero__grid">
        <div class="hero__copy">
          <p class="eyebrow" data-intro="eyebrow">Suco Frutatt · {f["name"]} 300 ml</p>
          <h1 id="hero-title" class="hero__title">
            {title_html(f["title_lines"])}
          </h1>
          <p class="hero__lead" data-intro="lead">{f["lead"]}</p>
          <div class="hero__ctas" data-intro="cta">
            <a class="btn" data-contact="whatsapp" data-msg="Olá! Quero pedir o Suco Frutatt {f["name"]}." hidden>Pedir pelo WhatsApp</a>
            <a class="btn btn--ghost" href="sabores.html">Ver todos os sabores</a>
          </div>
        </div>
        <div class="hero__product" data-depth="product" data-product>
          <span class="shadow" aria-hidden="true"></span>
          <div class="hero__float">
            {pic(f"prod-{f['slug']}", [320, 520, 760], "(max-width: 767px) 52vw, 400px", f"Garrafa de Suco Frutatt sabor {f['name']}, 300 ml", lazy=False, extra=f' style="view-transition-name: bottle-{f["slug"]}"')}
          </div>
        </div>
        <ul class="hero__facts" aria-label="Destaques do rótulo">
          {chips}
        </ul>
      </div>
      <div class="hero__near" data-leaves="near" aria-hidden="true"></div>
    </section>

    <section class="why" aria-labelledby="rotulo-title">
      <h2 id="rotulo-title" class="why__title">No rótulo.</h2>
      <ul class="why__list">
        {facts}
      </ul>
      <p class="why__note">{f["type"]} · 300 ml. Informações conforme o rótulo do produto.</p>
    </section>

    <a class="next" href="{nxt["slug"]}.html" data-flavor="{nxt["slug"]}">
      <span class="next__label">Próximo sabor</span>
      <span class="next__name">{nxt["name"]} <span class="next__arrow" aria-hidden="true">→</span></span>
    </a>'''
    return doc(f"Suco Frutatt {f['name']} — 300 ml", f["lead"], f["slug"], "sabores.html", body, preload)


def catalog():
    cards = []
    for f in FLAVORS:
        bg = bg_name(f["slug"]) if f["page"] else f"bg-{f['slug']}"
        img = pic(f"prod-{f['slug']}", [320, 520, 760], "(max-width: 767px) 58vw, 22vw",
                  f"Suco Frutatt {f['name']}",
                  extra=f' style="view-transition-name: bottle-{f["slug"]}"' if f["page"] else "")
        tag, close, attrs = ("a", "a", f' href="{f["slug"]}.html"') if f["page"] else ("div", "div", ' aria-disabled="true"')
        cards.append(f'''      <li class="card" data-flavor="{f["slug"]}" data-reveal-card>
        <{tag} class="card__link"{attrs}>
          <span class="card__bg" style="background-image: image-set(url('img/{bg}-960.avif') type('image/avif'), url('img/{bg}-960.webp') type('image/webp'))" aria-hidden="true"></span>
          <span class="card__product" data-product>
            <span class="shadow" aria-hidden="true"></span>
            <span class="prod__float">{img.replace("<picture>", '<picture class="prod__img">')}</span>
          </span>
          <span class="card__text">
            <span class="card__name">{f["name"]}</span>
            <span class="card__desc">{f["card"]}</span>
          </span>
        </{close}>
      </li>''')
    body = f'''    <section class="catalog" aria-labelledby="cat-title">
      <header class="catalog__head">
        <p class="eyebrow">Sabores</p>
        <h1 id="cat-title" class="catalog__title">
          <span class="line"><span class="word">Escolha</span> <span class="word">a</span> <span class="word accent">sua</span> <span class="word accent">fruta.</span></span>
        </h1>
      </header>
      <ul class="catalog__grid">
{chr(10).join(cards)}
      </ul>
    </section>'''
    return doc("Sabores — Suco Frutatt", "Todos os sabores do Suco Frutatt: Caju, Uva, Cajá e mais.", "caju", "sabores.html", body)


def contact():
    body = '''    <section class="contact" aria-labelledby="contato-title">
      <p class="eyebrow">Contato</p>
      <h1 id="contato-title" class="catalog__title">
        <span class="line"><span class="word">Fale</span> <span class="word">com</span> <span class="word">a</span> <span class="word accent">Frutatt.</span></span>
      </h1>
      <p class="contact__lead" data-reveal>Pedidos, revenda ou só um oi: chame a gente.</p>
      <div class="contact__actions" data-reveal>
        <a class="contact__btn contact__btn--wa" data-contact="whatsapp" data-msg="Olá! Vim pelo site da Frutatt." hidden>
          <strong>WhatsApp</strong><span data-contact-label="whatsapp"></span>
        </a>
        <a class="contact__btn contact__btn--ig" data-contact="instagram" hidden>
          <strong>Instagram</strong><span data-contact-label="instagram"></span>
        </a>
      </div>
      <p class="contact__empty" data-contact-empty hidden>Nossos canais estarão aqui em breve.</p>
    </section>'''
    return doc("Contato — Suco Frutatt", "Fale com a Frutatt pelo WhatsApp ou Instagram.", "caju", "contato.html", body)


def main():
    pages = {"sabores.html": catalog(), "contato.html": contact()}
    for i, f in enumerate(PAGES):
        pages[f"{f['slug']}.html"] = flavor_page(f, PAGES[(i + 1) % len(PAGES)])
    for name, html in pages.items():
        with open(os.path.join(SITE, name), "w", encoding="utf-8") as fh:
            fh.write(html)
    print("wrote:", ", ".join(pages))


if __name__ == "__main__":
    main()
